version: '3.8'

services:
  houer-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: houer-frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - houer-network

  houer-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: houer-frontend-dev
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
      - VITE_HMR_HOST=localhost
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - houer-network

networks:
  houer-network:
    driver: bridge
    name: houer-network
