services:
  houer-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: houer-frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - VITE_HMR_HOST=localhost
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - houer-network

networks:
  houer-network:
    driver: bridge
    name: houer-network
